version: "3.7"
services:
  server-src:
    image: registry.cn-shenzhen.aliyuncs.com/django-blog/blog-server-src-py:prod
    container_name: blog-server-src-py
    volumes:
      - blog-server-src-py:/link-src:consistent
    command: sh -c "cp_r.sh /home/src /link-src"
  py:
    image: registry.cn-shenzhen.aliyuncs.com/django-blog/blog-run-py:prod
    container_name: blog_py
    ports:
      - "8000:8000"
    volumes:
      - blog-server-src-py:/home/blog-server
    working_dir: /home/blog-server
    # restart: always
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
volumes:
  blog-server-src-py: